### ISSUE TITLE
not mined,

### ISSUE THREAD

**Issue by xziy** [volpcoin/Volpcoin#1]
With downloaded a purse, and included solo mining. But nothing happens. Then I set the minerd to solo mode ( ./cpuminer --algo x14 --scantime 10 --url 127.0.0.1:2221 --userpass 1:1 --threads 4 ) with the purse enabled, the mining is done but nothing is credited. 

wallet-qt message:  not staking because you don't have mature coins

**Comment by volpcoin** [comment]
If you locked your account, you can't mine. You have to unlock.

Step1: When you lock your account, there is a "unlock" on the tab of the wallet

Step2: Click on "unlock" 

Step3: It will show a message saying: "unlock wallet "

Step4 : Then enter your password , where is saying:"Enter Volp passphrase"

Step5 : After that, you can Start Mining

**Comment by xziy** [comment]
I can not find, there is no such thing here??!?
![_378](https://user-images.githubusercontent.com/19250425/27992822-eb895b70-64ad-11e7-9985-58889a7ac396.jpg)

**Comment by volpcoin** [comment]
I see that you don't have your wallet locked. So you need to wait the wallet sync all blocks first.After sync you can start mine

**Comment by xziy** [comment]
Sync done but nothing appeared

**Comment by volpcoin** [comment]
Can you take a screenshot of the tab that is saying "Stats" , so that i can see what is wrong?

**Comment by xziy** [comment]
![_379](https://user-images.githubusercontent.com/19250425/27993003-b50bb4e0-64b1-11e7-95bf-cd7a32a59c11.jpg)

**Comment by volpcoin** [comment]
Can you check if the "minerd" is inside the folder where is the volp-qt wallet.

**Comment by xziy** [comment]
![_380](https://user-images.githubusercontent.com/19250425/27993041-62e6de3c-64b2-11e7-91bc-31564a2c5f6e.jpg)

**Comment by volpcoin** [comment]
You don't need the cpuminer to mine.  The minerd already do that . You just need to go on the tab "Mine" , Select the type "Solo Mining" , select how many Threads you have  and then start to  mine.

**Comment by xziy** [comment]
Yes, it was already a whole night, but nothing was added.
Moreover, the blockchain does not show my address

**Comment by volpcoin** [comment]
Can you give me your Volp address on this email volpcoin.info@gmail.com . I will send a few coins for test.

**Comment by xziy** [comment]
done

**Comment by xziy** [comment]
Incoming transaction +260 VLP. But when I turned on solo mining nothing happens, writes 0 hashes. So it was before.

**Comment by volpcoin** [comment]
Did you have your firewall active? maybe the firewall is blocking the minerd.

**Comment by xziy** [comment]
solution: this Volp wallet run under Virtual machine, start minig on 1 thread solve problem. thanks

**Comment by DoFG** [comment]
Hi,
I have exactly the same issue:
My wallet is not locked/sync done/"minerd" is inside the folder where is the volp-qt wallet, BUT blockchain does not show my address (i've tried here http://explorer.volpcoin.eu/search (4 different address)), no one out of 3 mining options works (easy pool mining/solo mining/custom pool mining). "Miner started. You might not see any output for a few minutes" - that's all.
What should I do to resolve this issue?

**Comment by volpcoin** [comment]
Can you follow this steps and tell me what's happened after?

Go on the tab "Mine" , Select the type "Solo Mining" , select 1 Thread and then   start mine.

**Comment by DoFG** [comment]
"Solo mining started", nothing is happening later
![screenshot 28 _li](https://user-images.githubusercontent.com/30237178/28283892-f4320b2e-6b37-11e7-9b2d-de075da7aa3e.jpg)

**Comment by volpcoin** [comment]
Can you check if your firewall is blocking  the minerd?

**Comment by DoFG** [comment]
How to do this? I let access during first run. What exactly should I check?

**Comment by DoFG** [comment]
I've checked antivirus also and it seems to be ok with it

**Comment by volpcoin** [comment]
It's possible if you install TeamViewer and pass me your id and password on this email : volpcoin.info@gmail.com , so that i can try to help you?

**Comment by DoFG** [comment]
Sorry, I understand you want to help me, but I dont want to give someone access to my personal laptop. Just tell me what should I check and I will google it.

**Comment by volpcoin** [comment]
It's okay, I understand. All the procedements that you did are correct, maybe it's a problem on your system not in the wallet. Can you try to install a virtualbox- Ubuntu 14.04 and download the linux qt wallet and try to mine?

**Comment by DoFG** [comment]
Thanks. I will try, may be tomorrow and let you know. Does it help with firewall?

![screenshot 30](https://user-images.githubusercontent.com/30237178/28286462-e755e5d4-6b40-11e7-8cdb-2bfdd41a1f36.png)
![screenshot 29](https://user-images.githubusercontent.com/30237178/28286461-e752b5b2-6b40-11e7-88c2-7b3234829364.png)

**Comment by volpcoin** [comment]
It's all correct. Can you give me your Volp address on this email volpcoin.info@gmail.com . I will send a few coins for test.

**Comment by DoFG** [comment]
Sent

**Comment by DoFG** [comment]
Yes. I've receive 260+VCP. Thanks

**Comment by DoFG** [comment]
So, only one option left - virtual machine?

**Comment by volpcoin** [comment]
Ok. You should try  to mine on virtualbox , don't forget that is  the Ubuntu 14.04

**Comment by DoFG** [comment]
Ok. Thanks. Hope this problem will be resolved in the future.
I've tried mining on another laptop and have same issue, so it is not due to my laptop. 

PS. Transactions is really fast!!!

**Comment by volpcoin** [comment]
Try on Ubuntu 14. It's  have an old layout but it's a new protocol that we are testing.

**Comment by Catechin** [comment]
For those having an issue mining on Windows, here's a workaround: we want to start Volp-QT in server mode, so create a .bat file with the following:

Volp-qt.exe -server -rpcuser=1 -rpcpassword=1 -rpcport=8008

Use that to start the server.  Then, you can either download a cpu or gpu miner or use the included and solo mine.  As an example for the included minerd (or cpuminer-multi):

minerd.exe --algo x14 --scantime 10 --url 127.0.0.1:8008 --userpass 1:1 --threads 4

The port you use isn't too important, just pick something you don't use.

For reference I also had the same mining issue as reported here when using Ubuntu 14.04 on hyper-v or directly on Windows.

**Comment by DoFG** [comment]
Catechin, thanks a lot! It's running!!!
But, where to put wallet address? I have several address (obviously), how to choose right address for mining?

**Comment by Catechin** [comment]
You shouldn't need to put a wallet address in anywhere, it should just mine into your wallet directly.  What I find interesting is my mining goes to an address that's not even technically listed under my receive addresses.  But hey, it's working.

As an aside, I think solo mining via volp-qt may actually be working and it just my be reporting 0 hashes/s.  I'd rather mine in a way where I can see the console output though.  Maybe it would be a good idea to have the console output show up within the volp-qt wallet miner?

**Comment by DoFG** [comment]
Hey! Thanks again! YES-YES-YES!!! It's working! I've just received my first VCP directly to my wallet (it's still immature, but they exist). 
And yes it's great idea!
I just wanna say I'm absolutely new in mining, so first i read, watch youtube, then try, and only after that ask here or another place.
What do you know about difference in hash/rate between preinstall miner (i'm using that) vs another cpu miner (which one?) vs Gpu miner for mining that coin?
Thanks in advance

**Comment by Catechin** [comment]
Getting a bit off topic, but sure.  With an i5-2500k, if I remember correctly, I was getting something like 48-54 h/s with the stock miner.  Using the newest version of cpuminer-multi I could get 80h/s.  With ccminer and a GTX 970 with a slight undervolt and overclock (same performance as stock) I can get 5800h/s.  As long as a given algorithm has support for GPU mining it will theoretically always be more profitable to GPU mine.

And welcome to the mining game.  If you're really looking to learn, I'd encourage you to try setting up a basic Linux system (Ubuntu server would be my recommendation for ease and how many tutorials are out there).  Even if you choose to mine with windows, I think it's definitely worth getting comfortable with Linux.

**Comment by DoFG** [comment]
Is it https://github.com/tpruvot/cpuminer-multi ?
Can you write .bat file for running this mining?
And one more, should I put this miner to the same folder as a preinstalled miner?

**Comment by Catechin** [comment]
Yeah, that's the one.  The .bat file will be identical, just replace minerd.exe with the name of the cpuminer executable that most corresponds with your CPU.  The actual location of the miner doesn't matter as it's connecting to the rpc server via TCP.  For ease, it's best to have the .bat file and the miner in the same folder, but even that isn't mandatory.

**Comment by seregaost** [comment]
same problem..cant solo mine on 3 different computers

**Comment by volpcoin** [comment]
What is the system that you're using? Windows or Ubuntu?
How many Threads you put in the configuration? Did you tried  1 Threads first?

**Comment by seregaost** [comment]
win 10 64 bit
4 threads
Yes I try 1 Thread first
Managed to launch only through ccminer on 5*1060 rig

**Comment by xziy** [comment]
Join the pool testing!
http://vlp.m42.cx/
fee - 2%

**Comment by xziy** [comment]
Join the pool test
http://vlp.m42.cx
fee -2%

**Comment by KasteTX2** [comment]
I have similar problem. Wallet is unlocked, no problems with firewall, but miner dont work. I tried all the methods mentioned above to solve the problem, but nothing helped. Win 10 x64. 
With .bat file process of mining is indicated, but balance is zero. My adress VB6bUUhngFLQmXd3Yeq5BHcH3hXez4XGjL dont found in chain explorer.

**Comment by volpcoin** [comment]
Sorry for the delay. In relation to the mining, you need to select the "solo mining" and choose 1 thread at first.  The level of difficulty could also interferes with the difficulty of mining

If you don't mining , you could try to install Ubuntu 14.04 on a virtualbox and try to mine .

The Volpcoin Block Explorer identify only wallets that have some coins. We will sent to you 260 VCP of bonus.

Explorer: http://explorer.volpcoin.eu/address/VB6bUUhngFLQmXd3Yeq5BHcH3hXez4XGjL

**Comment by KasteTX2** [comment]
Thank you for response, I received coins. I put one stream in solo, processor is loaded, but the result is still zero. It's strange that at the current complexity of mining nothing is mined. Unfortunately, it is not possible to check mining on Ubuntu 14.04 at the moment. Can I use a video card separately? 

P.S. Despite the small amount of information, your project looks interesting, I will draw to it more members (+2 today :-)).

**Comment by volpcoin** [comment]
The  currency because of some implementations of the protocol, which is in the beta phase and is hybrid. It may not be very successful using a video card . But if you have the opportunity to access in the  TeamViewer so that we can help of somehow, if it's possible you can send  your ID and Password to this email:  volpcoin.info@gmail.com

**Comment by lucky626** [comment]
我今天刚下载钱包，请问能打赏点硬币给我？
VG89P9mEmHPKJbSVsSLF62nx8kqTfEfn6A
